[spirv] emit not preprocessed source code for `DebugSource`
google/DirectXShaderCompiler pull request #305
Opened 2020-05-01 22:02 UTC by jaebaek

This commit emits not preprocessed source code for `OpSource`
and `DebugSource`. Now it removes `#line` directives.

2020-05-06 16:13 UTC, ehsannas reviewed
It is OK to change the behavior of rich debug info for emitting (or not emitting) source. But it may not be ok to change the behavior for the `-fspv-debug=source` and `-Zi`. I know many devs use `-Zi`. We should check internally to see whether this is ok.

2020-05-06 16:13 UTC, ehsannas commented on tools/clang/lib/SPIRV/EmitVisitor.cpp
> +    dxc::DxcDllSupport dllSupport;
our fork of DXC currently doesn't have the Linux buildbots. Does this code compile on Linux?

2020-05-07 21:41 UTC, jaebaek commented
> It is OK to change the behavior of rich debug info for emitting (or not emitting) source. But it may not be ok to change the behavior for the `-fspv-debug=source` and `-Zi`. I know many devs use `-Zi`. We should check internally to see whether this is ok.

The main change is that this commit lets DXC emit **not preprocessed** source code while the existing DXC emits the preprocessed one. Do you think it still matters? Let me ask Hai about this issue.

2020-05-08 15:38 UTC, jaebaek commented on tools/clang/lib/SPIRV/EmitVisitor.cpp
> +    dxc::DxcDllSupport dllSupport;
Linux build works fine. I made build errors on Windows. I fixed the build failure. PTAL!

2020-05-08 15:39 UTC, jaebaek commented
Just for note, we had an offline discuss about the not preprocessed source code and concluded that it is fine.

2020-05-08 17:35 UTC, ehsannas requested changes
Please use WholeFileTest fixture so that we don't lose test coverage. Thanks

2020-05-08 17:35 UTC, ehsannas commented on tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp
> -TEST_F(FileTest, SpirvDebugControlSource) {
Why is this test removed?

2020-05-08 17:35 UTC, ehsannas commented on tools/clang/test/CodeGenSPIRV/spirv.debug.ctrl.line.hlsl
> -// CHECK-NOT:  OpModuleProcessed
why is this removed?

2020-05-08 21:28 UTC, jaebaek commented
As we discussed in offline, I implemented emitting multiple `OpSource` but removed `spirv.debug.ctrl.source.hlsl`. PTAL!

2020-05-11 17:22 UTC, ehsannas approved these changes
LGTM

2020-05-11 19:10 UTC, merged