[spirv] disable OpSource emission when DebugSource exists
google/DirectXShaderCompiler pull request #309
Opened 2020-05-21 21:02 UTC by jaebaek

2020-05-26 15:58 UTC, ehsannas requested changes
Correct me if I'm wrong:
There's no need to add more member variables or member functions. EmitVisitor has access to SpirvOptions. You can just check if `-fspv-debug==rich`, and if so, then don't emit OpSource.

2020-05-26 15:58 UTC, ehsannas commented on tools/clang/include/clang/SPIRV/SpirvModule.h
> +  // void clearSourcesIfDebugSourceExist();
unused code

2020-05-26 15:58 UTC, ehsannas commented on tools/clang/lib/SPIRV/EmitVisitor.cpp
> +  // if (debugSourceExists) return true;
unused code.

2020-05-26 18:53 UTC, jaebaek reviewed
I agree. I removed members and member functions. It uses `spvOptions.debugInfoRich` instead.

2020-05-26 18:53 UTC, jaebaek commented on tools/clang/include/clang/SPIRV/SpirvModule.h
> +  // void clearSourcesIfDebugSourceExist();
removed

2020-05-26 18:53 UTC, jaebaek commented on tools/clang/lib/SPIRV/EmitVisitor.cpp
> +  // if (debugSourceExists) return true;
removed

2020-05-26 19:47 UTC, ehsannas commented on tools/clang/lib/SPIRV/EmitVisitor.cpp
> +  if (spvOptions.debugInfoRich)
Please add a comment here:
```cpp
// We should either emit OpSource or DebugSource, not both.
// Therefore if rich debug info is being generated, we will skip emitting OpSource.
```

2020-05-27 20:18 UTC, jaebaek commented on tools/clang/lib/SPIRV/EmitVisitor.cpp
> +  if (spvOptions.debugInfoRich)
done

2020-05-27 21:28 UTC, ehsannas approved these changes
Thanks

2020-05-27 21:29 UTC, merged